[[constraint]]
  name = "github.com/bmatsuo/lmdb-go"
  version = "1.8.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"
